dotnet:
  - '**/*.cs'
  - '**/*.fs'
  - '**/*.vb'
  - '**/*.sln'


tests:
  - '**/*Test*.cs'
  - '**/*Tests/*.cs'
  - '**/*.spec.cs'

infra:
  - '**/*.yaml'
  - '**/*.yml'
  - '**/*.tf'
  - '**/Dockerfile'

ci/cd:
  - '.github/**/*'

docs:
  - '**/*.md'
